### PR TITLE
WIP:  Added TCP Client

### PR DESCRIPTION
**Pull request by ardave**
There are a couple of commits here, which I can squash but preferred to leave them distinct for now in case one of them in particular needs to be tossed out.

I had to make a change to get the code to compile out of source control, but I am uncertain whether that change is correct.

I moved the F# code over and here have thus far done just the minimum to get the solution to build.

### CODE REVIEW

**Comment by ardave** [comment]
Also, may I ask the overarching purpose of this (nblockchain) organization and this repo?  I'm guessing it is to make some of these lower-level components reusable by the public at-large, but I'll still ask to confirm.   

The C# code has come from the Nethereum repo?  What is its intended future state?

**Comment by ardave** [comment]
Added another commit to support an Option<CancellationToken>, but have a look at it and see if it matches your intentions.

**Comment by ardave** [comment]
> C# coding on the projects that come from Nethereum: the idea is to change the Async methods to accept an optional CancellationToken. If supplied (not null), then the code will use that when calling the underlying transport async tasks (e.g. BCL's HttpClient).


Is this to say you would like for me to begin making these changes to the C# code?  If so, I might use something like CancellationToken.None, as CancellationToken is a struct and can't really be null.

**Comment by knocte** [comment]
> There are a couple of commits here, which I can squash but preferred to leave them distinct for now in case one of them in particular needs to be tossed out.

No need to be squashed because each serves its own purpose and single unit of work, so it's perfect now.

> I had to make a change to get the code to compile out of source control, but I am uncertain whether that change is correct.

Seems correct.

> The C# code has come from the Nethereum repo? What is its intended future state?

The idea is that by adding cancelation token support to the RPC libs of Nethereum, we make a case for Nethereum to rather adopt JsonRpcSharp (and maybe even NBitcoin at some point).

> Added another commit to support an Option, but have a look at it and see if it matches your intentions.

Can you remove any cancellationToken-related work from this PR and park it somewhere to propose it later as a second PR? I want this PR only to add the F# code (as it is in geewallet) and the build fix.

> Is this to say you would like for me to begin making these changes to the C# code? If so, I might use something like CancellationToken.None, as CancellationToken is a struct and can't really be null.

Yes sounds good.

**Comment by knocte** [comment]
Code review bits to address, only two:

- Don't include the LegacyTcpClient please (as a consequence of this, no need to include Config.fs either).
- Rename FsClient to TcpClient please (in project name and file name).

**Comment by ardave** [comment]
I don't completely understand why this PR shows me pushing 8 commits, only 1 of which is from me.

I can guess:  If I do N commits, then to squash them I run git `rebase -i HEAD~Y` where Y is some number much larger than N, so that I don't have to count N commits, nor do I have to worry about off-by-one errors.

Then in the interactive rebase file, I use **s** to squash all of my commits, leaving other people's previous commits with the default **pick** option.  Perhaps doing this causes new SHAs to be assigned to the commits that precede my own?  

If you can confirm, that would be an annoying behavior on Git's part, but at least my mental model would be accurate.

But also if that is the case, I do not know how to resolve the issue with this PR aside from just deleting and recreating my fork, which would likely cause all of this conversation to be lost.

**Comment by knocte** [comment]
Hey. When squashing 2 commits into 1, you don't have to mark 2 commits with
's' but just one (the last one), so when squashing 3 into 1, mark 2 and so
on. Also if you made let's say 3 commits on top of master, when rebasing
you have to use HEAD~3, if you use more than 3 you may destroy previous
history and make github confused, showing more commits than it should be.
Last thing, this conversation will never be lost. You could create a new
fresh clone, then create a branch with same name as the one you used for
this PR, recreate the work, and then push with force (-f) to overwrite
previous work in the PR.
Let me know if you have more doubts.

**Comment by knocte** [comment]
Applied 2 patches manually from this PR on top of master, thanks!

**Pull request closed without merging**
