### PR TITLE
Target 4.6.1 instead of 4.6, remove System.Net.Http Nuget reference

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by knocte** [comment]
Can you please split this in 2 commits (but same PR, no prob).

**Comment by ysangkok** [comment]
@knocte fixed.

**Comment by ysangkok** [comment]
@knocte rebased

**Comment by knocte** [comment]
> @knocte rebased

Sorry for the mess! I've pushed with force and shit like that. Bear with me, I'll try to get this sorted out, don't waste time on this hehe

**Comment by knocte** [comment]
I extracted the removal of System.Net.Http nuget ref here: https://github.com/nblockchain/JsonRpcSharp/commit/469146b121b92292b8271b820366c0b7c46c2fe7

I didn't push the 4.6.1 to 4.6 change though. I don't remember why, maybe because there was no reason for it? But also, it was actually not desired, since our Nethereum fork uses 4.6 (not 4.6.1). Thanks

**Pull request closed without merging**
