### PR TITLE
All Clients:  Added optional CancellationToken support

### PR DESCRIPTION
**Pull request by ardave**
All Clients:  Added optional CancellationToken support to existing async methods

### CODE REVIEW

**Comment by knocte** [comment]
Good work! 2 nitpicks:
- Can you add cancellation token support for the TCP client as well please? (The F# code you had used initially in the previous PR.)
- Can you separate the int milliseconds -> TimeSpan conversion into its own commit?
Thanks!

**Comment by knocte** [comment]
Actually, disregard the second nitpick above, as I see it was an improvement kinda related to cancellation support. Just add the F# changes and I'll merge this thanks!

**Comment by ardave** [comment]
So ... I deleted my fork and lost the branch with that work in it.  So I have recreated it, however it does not feel the same.  Plz let me know what you think.

**Comment by knocte** [comment]
Why doesn't it feel the same? Looks good :) Merging.

**Pull request merged**
