### PR TITLE
Packaging: include all dlls for net461 and netstandard2.0 targets

### PR DESCRIPTION
**Pull request by mfkl**
Note: Added 3 missing SocketTaskExtensions for the JsonRpcSharp.UnixIpcClient on net461

### CODE REVIEW

**Comment by knocte** [comment]
@mfkl interesting thing I found while digging my past commits is that I fixed the SocketTaskExtensions issue already in the past, but with a different technique, and in a different project (I fixed it in the `IpcClient` project, you fixed it in the `UnixIpcClient` project): https://github.com/Nethereum/Nethereum/commit/9c116902d247eb85d52d58558a005bb138d5bab7

And now I see that in this PR you're actually eliminating the NET461 constant from the IpcClient project (essentially reverting my fix from Feb2018), so... this makes me wonder, how is it possible that you didn't face the same build issue for `IpcClient`?

PS: side-note unrelated to the above: I'm wondering if we actually can downgrade JsonRpcSharp from net461 to net460.

**Comment by mfkl** [comment]
> you're actually eliminating the NET461 constant

Ops... Yeah didn't think about it twice.


> how is it possible that you didn't face the same build issue for `IpcClient`?

Because the code that uses these extension methods and gives build error was once in `IpcClient` but now has moved to `UnixIpcClient`. https://github.com/Nethereum/Nethereum/blob/9c116902d247eb85d52d58558a005bb138d5bab7/src/Nethereum.JsonRpc.IpcClient/UnixIpcClient.cs

**Comment by knocte** [comment]
> https://github.com/Nethereum/Nethereum/blob/9c116902d247eb85d52d58558a005bb138d5bab7/src/Nethereum.JsonRpc.IpcClient/UnixIpcClient.cs

That link points to the **IpcClient** project ;) I'm talking about projects here, not files :)

I'm barely waking up now, let me look into this better in a bit when I dig a bit more.

**Comment by mfkl** [comment]
> That link points to the **IpcClient** project ;) I'm talking about projects here, not files :)

Regardless. As of this writing, the only project that has code calling the `SocketTaskExtensions` methods is the `JsonRpcSharp.UnixIpcClient` project. Which is why only this project failed to build in net461.

Looking at https://github.com/Nethereum/Nethereum/blob/9c116902d247eb85d52d58558a005bb138d5bab7/src/Nethereum.JsonRpc.IpcClient/UnixIpcClient.cs, it seems that the previous solution was to #ifdef net461 and use the regular socket APIs in that case.

**Pull request merged**
